### ISSUE TITLE
Working with non-model organisms

### ISSUE THREAD

**Issue by madzafv** [tanghaibao/quota-alignment#12]
Hi!
I want to check for synteny between the zebra finch genome available at ensembl and a the genome of another finch, which is still unpublished and was ensembled, mapped and annotated by a collaborator  using several sources.
Can quota-alignment help me?
Or would you recommend any other tool that could?
LASTZ, Mummer, SyMAP, Satsuma, SynMap, Enredo/Pecan, HAL...
Thanks!

**Comment by tanghaibao** [comment]
@madzayasodara Probably the easiest way is to upload your genome onto [CoGe](https://genomevolution.org/coge/), which contains an implementation of QUOTA-ALIGN, plus some other tools including SynMap (synteny viewer) and GeVo (local synteny browser). Please feel free to contact the CoGe developers if you run into issues.

Haibao
