### ISSUE TITLE
No gff file for -sbed option in blast_to_raw.py

### ISSUE THREAD

**Issue by Ginsea** [tanghaibao/quota-alignment#6]
Dear Dr.
Thanks for your great scripts, and its helpful for my project. Now I want to filter some seqs which C-score lower than 0.5 after genome annotation. I mapped the gene models proteins to a protein database (which contained several species gene models which have been published), and I have no gff file for this protein database. So my question is how to use blast_to_raw.py if gff file for -sbed option is not available. Thanks for your help!

**Comment by tanghaibao** [comment]
HI @Ginsea,

Is it possible to get the position information for those proteins? Then you could probably generate your own BED file, which can be formatted with just chr, start, end, geneid columns.

Haibao
