### ISSUE TITLE
--quota=1:4 or --quota=4:1?

### ISSUE THREAD

**Issue by zengxiaofei** [tanghaibao/quota-alignment#7]
Dear Dr. Tang,

It seems something wrong with the code in README.rst > Pre- and post-processing > BLAST filtering:

`quota_align.py --format=raw --merge --Dm=20 --min_size=5 --quota=1:4 athaliana_grape.raw`

`--quota=1:4` or should be `--quota=4:1` ?

Because the genome of _Arapidopsis_ underwent two rounds of WGD after γ.

Thanks for your attention.
Xiaofei Zeng

**Comment by tanghaibao** [comment]
@zengxiaofei thanks for pointing that out - I'm committed a fix for this. Haibao
